-- ## Motoshop ##

-- CREATE DATABASE MOTOSHOP;
use p2g5;

-- DELETE SECTION --
DROP TABLE RENT;
DROP TABLE RENTABLE_BIKE;
DROP TABLE MOTO_STATION;
DROP TABLE OWNED_BIKE;
DROP TABLE SALE;
DROP TABLE SALESMAN;
DROP TABLE CHANGED_PARTS;
DROP TABLE REVISION;
DROP TABLE MECHANIC;
DROP TABLE WORKSHOP;
DROP TABLE STOCK_BIKE;
DROP TABLE STAND;
DROP TABLE STAFF_MEMBER;
DROP TABLE CLIENT;
DROP TABLE MOTORCYCLE;
DROP TABLE PART;

-- CREATE SECTION --
CREATE TABLE MOTORCYCLE(
	FRAME_NO			INT,
	MODEL				VARCHAR(10),
	BRAND				VARCHAR(10)	NOT NULL,
	YEAR				INT			NOT NULL,
	CC					INT			NOT NULL,
	HP					INT			NOT NULL,
	PRIMARY KEY(FRAME_NO)
);
-- changes
ALTER TABLE MOTORCYCLE ALTER COLUMN MODEL varchar(20);
ALTER TABLE MOTORCYCLE ALTER COLUMN BRAND varchar(20);


CREATE TABLE MOTO_STATION(
	NUMBER			INT IDENTITY(1,1),
	LOCALIZATION	VARCHAR(100)		NOT NULL,
	CAPACITY		INT,
	PRIMARY KEY(NUMBER)
);


CREATE TABLE RENTABLE_BIKE(
	FRAME_NO			INT,
	PRICE_KM			INT			NOT NULL,
	TOTAL_KM			INT,
	MOTO_STATION		INT			NOT NULL, -- HAS TO BE IN A MOTOSTATION
	PRIMARY KEY(FRAME_NO),
	FOREIGN KEY(FRAME_NO) REFERENCES MOTORCYCLE(FRAME_NO) ON DELETE CASCADE,
	FOREIGN KEY(MOTO_STATION) REFERENCES MOTO_STATION(NUMBER)
);


CREATE TABLE STOCK_BIKE(
	FRAME_NO			INT,
	PRICE				INT			NOT NULL,
	STAND				INT			NOT NULL, -- HAS TO BE IN A STAND
	PRIMARY KEY(FRAME_NO),
	FOREIGN KEY(FRAME_NO) REFERENCES MOTORCYCLE(FRAME_NO) ON DELETE CASCADE
	-- FOREIGN KEY(STAND) REFERENCES STAND(NUMBER),
);


CREATE TABLE OWNED_BIKE(
	FRAME_NO			INT,
	LICENSE_PLATE		INT			NOT NULL,
	TOTAL_KM			INT,
	B_OWNER				INT			NOT NULL, -- HAS TO HAVE AN OWNER
	PRIMARY KEY(FRAME_NO),
	FOREIGN KEY(FRAME_NO) REFERENCES MOTORCYCLE(FRAME_NO)
	--FOREIGN KEY(B_OWNER) REFERENCES CLIENT(NIF),
);


CREATE TABLE STAND(
	NUMBER				INT IDENTITY(1,1),
	LOCALIZATION		VARCHAR(100)		NOT NULL,
	PRIMARY KEY(NUMBER)
);

CREATE TABLE CLIENT(
	NIF					INT,
	C_NAME				VARCHAR(30)		NOT NULL,
	C_ADDRESS			VARCHAR(30)		NOT NULL,
	PRIMARY KEY(NIF)
);
-- changes
ALTER TABLE CLIENT ALTER COLUMN C_ADDRESS varchar(150);


CREATE TABLE WORKSHOP(
	NUMBER				INT IDENTITY(1,1),
	LOCALIZATION		VARCHAR(100)		NOT NULL,
	PRIMARY KEY(NUMBER)
);

CREATE TABLE STAFF_MEMBER(
	NUMBER				INT IDENTITY(100,1),
	S_NAME				VARCHAR(20)			NOT NULL,
	S_ADDRESS			VARCHAR(150)		NOT NULL,
	PRIMARY KEY(NUMBER)
);

CREATE TABLE SALESMAN(
	NUMBER				INT,
	WORK_STAND			INT,
	PRIMARY KEY(NUMBER),
	FOREIGN KEY(NUMBER) REFERENCES STAFF_MEMBER(NUMBER),
	FOREIGN KEY(WORK_STAND) REFERENCES STAND(NUMBER) ON DELETE CASCADE
);

CREATE TABLE MECHANIC(
	NUMBER				INT,
	WORK_WORKSHOP		INT,
	PRIMARY KEY(NUMBER),
	FOREIGN KEY(NUMBER) REFERENCES STAFF_MEMBER(NUMBER),
	FOREIGN KEY(WORK_WORKSHOP) REFERENCES WORKSHOP(NUMBER) ON DELETE CASCADE
);

CREATE TABLE REVISION(
	REVISION_NO			INT IDENTITY(1000,1),
	FRAME_NO			INT,
	R_DATE				DATE,
	PRICE				INT,
	--WORKSHOP			INT,
	MECHANIC			INT,
	PRIMARY KEY(REVISION_NO),
	FOREIGN KEY(FRAME_NO) REFERENCES MOTORCYCLE(FRAME_NO) ON DELETE SET NULL,
	--FOREIGN KEY(WORKSHOP) REFERENCES WORKSHOP(NUMBER) ON DELETE SET NULL,
	FOREIGN KEY(MECHANIC) REFERENCES MECHANIC(NUMBER) ON DELETE SET NULL
);

CREATE TABLE PART(
	NUMBER			INT,
	PART_TEXT		VARCHAR(30)		NOT NULL,

	PRIMARY KEY(NUMBER)

);

CREATE TABLE CHANGED_PARTS(
	REVISION_NO			INT,
	PART				INT,
	PRIMARY KEY(REVISION_NO, PART),
	FOREIGN KEY(REVISION_NO) REFERENCES REVISION(REVISION_NO) ON DELETE CASCADE,
	FOREIGN KEY(PART) REFERENCES PART(NUMBER)
);

CREATE TABLE RENT(
	FRAME_NO			INT,
	R_DATE				DATE,
	CLIENT				INT,
	PRIMARY KEY(FRAME_NO, R_DATE),
	FOREIGN KEY(FRAME_NO) REFERENCES RENTABLE_BIKE(FRAME_NO) ON DELETE CASCADE,
	FOREIGN KEY(CLIENT) REFERENCES CLIENT(NIF) ON DELETE CASCADE
);

CREATE TABLE SALE(
	INVOICE_NO			INT IDENTITY(1000,1),
	CLIENT				INT,
	MOTORCYCLE			INT,
	SELLER				INT,
	PRIMARY KEY(INVOICE_NO),
	FOREIGN KEY(CLIENT) REFERENCES CLIENT(NIF),
	FOREIGN KEY(MOTORCYCLE) REFERENCES MOTORCYCLE(FRAME_NO) ON DELETE SET NULL,
	FOREIGN KEY(SELLER) REFERENCES SALESMAN(NUMBER) ON DELETE SET NULL,
);



ALTER TABLE SALE ADD PRICE INT;	
ALTER TABLE SALE ADD S_DATE DATE; 

ALTER TABLE OWNED_BIKE
	ADD CONSTRAINT BIKE_OWNER FOREIGN KEY(B_OWNER) REFERENCES CLIENT(NIF);

ALTER TABLE STOCK_BIKE
	ADD CONSTRAINT BIKE_IN_STAND FOREIGN KEY(STAND) REFERENCES STAND(NUMBER) ON DELETE CASCADE;


-- Check constraints 311426219
ALTER TABLE MOTORCYCLE ADD CHECK(FRAME_NO > 100000000 AND FRAME_NO < 1000000000); 
ALTER TABLE MOTORCYCLE ADD CHECK(YEAR > 1900 AND YEAR <= YEAR(getdate()));
ALTER TABLE MOTORCYCLE ADD CHECK(CC > 0 AND CC < 5000);
ALTER TABLE MOTORCYCLE ADD CHECK(HP > 0 AND HP < 1000);

ALTER TABLE MOTO_STATION ADD CHECK(CAPACITY > 0);

ALTER TABLE RENTABLE_BIKE ADD CHECK(PRICE_KM > 0);
ALTER TABLE RENTABLE_BIKE ADD CHECK(TOTAL_KM > 0);

ALTER TABLE STOCK_BIKE ADD CHECK(PRICE > 0);

-- assumindo uma matricula numérica apenas, para simplificar
ALTER TABLE OWNED_BIKE ADD CHECK(LICENSE_PLATE > 0);
ALTER TABLE OWNED_BIKE ADD CHECK(TOTAL_KM >= 0);

ALTER TABLE REVISION ADD CHECK(PRICE > 0);

ALTER TABLE CHANGED_PARTS ADD CHECK(PART > 0);

--ALTER TABLE OWNED_BIKE DROP CONSTRAINT CK__OWNED_BIK__TOTAL__1CBC4616