use MOTOSHOP;

-- Getting all bikes of each owner
SELECT C_NAME, BRAND + ' ' + MODEL + ' ' + CONVERT(varchar, CC) AS Motorcycle
FROM ((CLIENT JOIN OWNED_BIKE ON NIF=B_OWNER)
JOIN MOTORCYCLE ON MOTORCYCLE.FRAME_NO=OWNED_BIKE.FRAME_NO);

-- Getting all bikes selling in each stand
SELECT LOCALIZATION, BRAND + ' ' + MODEL + ' ' + CONVERT(varchar, CC) AS Motorcycle
FROM ((STAND JOIN STOCK_BIKE ON STAND.NUMBER=STOCK_BIKE.STAND)
JOIN MOTORCYCLE ON MOTORCYCLE.FRAME_NO=STOCK_BIKE.FRAME_NO)
ORDER BY LOCALIZATION DESC;

-- Getting the mechanic, the motorcycle and the owner of 
-- a motorcycle of each revision and the changed parts
SELECT LOCALIZATION as Workshop, M_NAME AS Revision_Mechanic, 
BRAND + ' ' + MODEL + ' ' + CONVERT(varchar, CC) AS Motorcycle, 
C_NAME AS Client_Name, PART
FROM (((((((REVISION JOIN MECHANIC ON REVISION.MECHANIC=MECHANIC.NUMBER)
JOIN STAFF_MEMBER ON MECHANIC.NUMBER = STAFF_MEMBER.NUMBER)
JOIN WORKSHOP ON REVISION.WORKSHOP=WORKSHOP.NUMBER)
JOIN OWNED_BIKE ON REVISION.FRAME_NO=OWNED_BIKE.FRAME_NO)
JOIN MOTORCYCLE ON MOTORCYCLE.FRAME_NO=OWNED_BIKE.FRAME_NO)
JOIN CLIENT ON OWNED_BIKE.B_OWNER=CLIENT.NIF)
JOIN CHANGED_PARTS ON REVISION.FRAME_NO=CHANGED_PARTS.FRAME_NO)

-- Getting all rentable motorcycles in a motostation
SELECT LOCALIZATION AS Motostation, BRAND + ' ' + MODEL + ' ' + CONVERT(varchar, CC) AS Motorcycle
FROM ((MOTO_STATION JOIN RENTABLE_BIKE ON MOTO_STATION.NUMBER=RENTABLE_BIKE.MOTO_STATION)
JOIN MOTORCYCLE ON RENTABLE_BIKE.FRAME_NO=MOTORCYCLE.FRAME_NO);

-- Client rents
SELECT C_NAME As Client, BRAND + ' ' + MODEL + ' ' + CONVERT(varchar, CC) AS Motorcycle, R_DATE as Rent_Date
FROM ((CLIENT JOIN RENT ON CLIENT.NIF = RENT.CLIENT)
JOIN MOTORCYCLE ON RENT.FRAME_NO=MOTORCYCLE.FRAME_NO);

-- Salesman sales
SELECT M_NAME As Salesman, C_NAME As Client,  
BRAND + ' ' + MODEL + ' ' + CONVERT(varchar, CC) AS Motorcycle,
PRICE As Price
FROM (((((SALE JOIN SALESMAN ON SELLER=SALESMAN.NUMBER)
JOIN STAFF_MEMBER ON STAFF_MEMBER.NUMBER=SALESMAN.NUMBER)
JOIN STOCK_BIKE ON STOCK_BIKE.FRAME_NO = SALE.MOTORCYCLE)
JOIN MOTORCYCLE ON MOTORCYCLE.FRAME_NO = STOCK_BIKE.FRAME_NO)
JOIN CLIENT ON CLIENT.NIF=SALE.CLIENT);

-- Total sales of each salesman of each stand
SELECT LOCALIZATION As Stand, Salesman, MAX(Total_Sales) As Top_Seller_Sales
FROM (((SALESMAN_SALES JOIN STAFF_MEMBER ON Salesman=M_NAME)
JOIN SALESMAN ON STAFF_MEMBER.NUMBER=SALESMAN.NUMBER)
JOIN STAND ON SALESMAN.WORK_STAND=STAND.NUMBER)
GROUP BY LOCALIZATION, Salesman;

-- REVISIONS

-- Basic Info
SELECT R_DATE as RevDate, BRAND + ' ' + MODEL + ' ' + CONVERT(varchar, CC) as Motorcycle
	FROM REVISION JOIN MOTORCYCLE ON REVISION.FRAME_NO = MOTORCYCLE.FRAME_NO;

-- Complete Info
SELECT Revision.R_DATE as RevDate, BRAND + ' ' + MODEL + ' ' + CONVERT(varchar, CC) AS Motorcycle, 
	C_NAME AS Client_Name, LOCALIZATION as Workshop, M_NAME AS Revision_Mechanic, COUNT(*) as parts	
	FROM (((((((REVISION JOIN MECHANIC ON REVISION.MECHANIC=MECHANIC.NUMBER)
	JOIN STAFF_MEMBER ON MECHANIC.NUMBER = STAFF_MEMBER.NUMBER)
	JOIN WORKSHOP ON REVISION.WORKSHOP=WORKSHOP.NUMBER)
	JOIN OWNED_BIKE ON REVISION.FRAME_NO=OWNED_BIKE.FRAME_NO)
	JOIN MOTORCYCLE ON MOTORCYCLE.FRAME_NO=OWNED_BIKE.FRAME_NO)
	JOIN CLIENT ON OWNED_BIKE.B_OWNER=CLIENT.NIF)
	JOIN CHANGED_PARTS ON REVISION.FRAME_NO=CHANGED_PARTS.FRAME_NO)
	GROUP BY Revision.R_DATE, LOCALIZATION, M_NAME, BRAND, MODEL, CC, C_NAME

-- Sales from salesman
SELECT INVOICE_NO AS INVOICE, S_DATE AS Date,  BRAND + ' ' + MODEL + ' ' + CONVERT(varchar, CC) AS Motorcycle,
	C_NAME AS Client, STOCK_BIKE.PRICE AS Price
	FROM (((((SALE JOIN SALESMAN ON SELLER=SALESMAN.NUMBER)
	JOIN STAFF_MEMBER ON STAFF_MEMBER.NUMBER=SALESMAN.NUMBER)
	JOIN STOCK_BIKE ON STOCK_BIKE.FRAME_NO = SALE.MOTORCYCLE)
	JOIN MOTORCYCLE ON MOTORCYCLE.FRAME_NO = STOCK_BIKE.FRAME_NO)
	JOIN CLIENT ON CLIENT.NIF=SALE.CLIENT)
	WHERE SALESMAN.NUMBER=696

-- Revisions from mechanic
SELECT REVISION.R_DATE AS Date, BRAND + ' ' + MODEL + ' ' + CONVERT(varchar, CC) AS Motorcycle, 
	C_NAME AS Client, PRICE AS Price, COUNT(*) AS Changed_Parts
	FROM (((((((REVISION JOIN MECHANIC ON REVISION.MECHANIC=MECHANIC.NUMBER)
	JOIN STAFF_MEMBER ON MECHANIC.NUMBER = STAFF_MEMBER.NUMBER)
	JOIN WORKSHOP ON REVISION.WORKSHOP=WORKSHOP.NUMBER)
	LEFT OUTER JOIN OWNED_BIKE ON REVISION.FRAME_NO=OWNED_BIKE.FRAME_NO)
	JOIN MOTORCYCLE ON MOTORCYCLE.FRAME_NO=REVISION.FRAME_NO)
	LEFT OUTER JOIN CLIENT ON OWNED_BIKE.B_OWNER=CLIENT.NIF)
	JOIN CHANGED_PARTS ON REVISION.FRAME_NO=CHANGED_PARTS.FRAME_NO)
	GROUP BY REVISION.R_DATE, BRAND, MODEL, CC, C_NAME, PRICE