CREATE SCHEMA ex4f;
GO

DROP TABLE IF EXISTS ex4f.Prof_Participa;
DROP TABLE IF EXISTS ex4f.Est_Participa;
DROP TABLE IF EXISTS ex4f.Projeto;
DROP TABLE IF EXISTS ex4f.Graduado;
DROP TABLE IF EXISTS ex4f.Departamento;
DROP TABLE IF EXISTS ex4f.Professor;
DROP SCHEMA IF EXISTS ex4f;

CREATE TABLE ex4f.Professor(
	NMEC				INT,
	NOME				VARCHAR(20),
	AREA				VARCHAR(20),
	CATEGORIA			VARCHAR(20),
	NASC				DATE,
	DEPARTAMENTO		VARCHAR(20)		NOT NULL,
	DEDICACAO			INT				CHECK(DEDICACAO > 0 AND DEDICACAO <= 100),

	PRIMARY KEY(NMEC)
);

CREATE TABLE ex4f.Departamento(
	NOME				VARCHAR(20),
	MORADA				VARCHAR(20),
	DIRIGENTE			INT,

	PRIMARY KEY(NOME),
	FOREIGN KEY(DIRIGENTE) REFERENCES ex4f.Professor(NMEC)
);

--ALTER TABLE ex4f.Professor
	--ADD CONSTRAINT TRABALHA FOREIGN KEY(DEPARTAMENTO) REFERENCES ex4f.Departamento(NOME);

CREATE TABLE ex4f.Graduado(
	NMEC				INT,
	NOME				VARCHAR(20),
	NASC				DATE,
	SUPERVISOR			INT				NOT NULL,
	DEPARTAMENTO		VARCHAR(20)		NOT NULL,
	GRAU				VARCHAR(20),
	CONSELHEIRO			INT				NOT NULL,

	PRIMARY KEY(NMEC),
	FOREIGN KEY(SUPERVISOR) REFERENCES ex4f.Professor(NMEC),
	FOREIGN KEY(DEPARTAMENTO) REFERENCES ex4f.Departamento(NOME),
	FOREIGN KEY(CONSELHEIRO) REFERENCES ex4f.Graduado(NMEC)
);

CREATE TABLE ex4f.Projeto(
	ID					INT,
	NOME				VARCHAR(20),
	ORÇAMENTO			INT,
	ENT_FIN				VARCHAR(20),
	INIT_DATE			DATE,
	EXIT_DATE			DATE,
	GESTOR				INT				NOT NULL,

	PRIMARY KEY(ID),
	FOREIGN KEY(GESTOR) REFERENCES ex4f.Professor(NMEC)
);

CREATE TABLE ex4f.Est_Participa(
	NMEC				INT,
	PROJETO				INT,

	PRIMARY KEY(NMEC, PROJETO),
	FOREIGN KEY(NMEC) REFERENCES ex4f.Graduado(NMEC),
	FOREIGN KEY(PROJETO) REFERENCES ex4f.Projeto(ID)
);

CREATE TABLE ex4f.Prof_Participa(
	NMEC				INT,
	PROJETO				INT,

	PRIMARY KEY(NMEC, PROJETO),
	FOREIGN KEY(NMEC) REFERENCES ex4f.Professor(NMEC),
	FOREIGN KEY(PROJETO) REFERENCES ex4f.Projeto(ID)
);


