rm -rf dirBar/clientSide/
rm -rf dirBar/commInfra/
rm -rf dirBar/interfaces/
rm -rf dirBar/serverSide/
rm -rf dirKitchen/clientSide/
rm -rf dirKitchen/commInfra/
rm -rf dirKitchen/interfaces/
rm -rf dirKitchen/serverSide/
rm -rf dirTable/clientSide/
rm -rf dirTable/commInfra/
rm -rf dirTable/interfaces/
rm -rf dirTable/serverSide/
rm -rf dirGeneralRepos/clientSide/
rm -rf dirGeneralRepos/commInfra/
rm -rf dirGeneralRepos/interfaces/
rm -rf dirGeneralRepos/serverSide/
rm -rf dirChef/clientSide/
rm -rf dirChef/commInfra/
rm -rf dirChef/interfaces/
rm -rf dirStudent/clientSide/
rm -rf dirStudent/commInfra/
rm -rf dirStudent/interfaces/
rm -rf dirWaiter/clientSide/
rm -rf dirWaiter/commInfra/
rm -rf dirWaiter/interfaces/
rm -rf dirRegistry/commInfra/
rm -rf dirRegistry/interfaces/
rm -rf dirRegistry/serverSide/
rm -rf dirRMIRegistry/commInfra/
rm -rf dirRMIRegistry/interfaces/
