CREATE SCHEMA ex53;

-- Delete Section
DROP TABLE ex53.Venda;
DROP TABLE ex53.Farmacia;
DROP TABLE ex53.Farmaco;
DROP TABLE ex53.Farmaceutica;
DROP TABLE ex53.Prescricao;
DROP TABLE ex53.Medico;
DROP TABLE ex53.Paciente;

-- Init Section
CREATE TABLE ex53.Medico(
	SNS				INT,
	NOME			VARCHAR(20)		NOT NULL,
	ESPECIALIDADE	VARCHAR(20),

	PRIMARY KEY(SNS)
);

CREATE TABLE ex53.Paciente(
	NR_UTENTE		INT,
	NOME			VARCHAR(20)		NOT NULL,
	DATA_NASC		DATE			NOT NULL,
	ENDERECO		VARCHAR(20),

	PRIMARY KEY(NR_UTENTE)
);

CREATE TABLE ex53.Prescricao(
	NUMERO			INT,
	MEDICO			INT		NOT NULL,
	PACIENTE		INT		NOT NULL,

	PRIMARY KEY(NUMERO),
	FOREIGN KEY(MEDICO) REFERENCES ex53.Medico(SNS),
	FOREIGN KEY(PACIENTE) REFERENCES ex53.Paciente(NR_UTENTE)
);

CREATE TABLE ex53.Farmaceutica(
	NUMERO			INT,
	NOME			VARCHAR(20)		NOT NULL,
	ENDERECO		VARCHAR(20)		NOT NULL,
	TELEFONE		VARCHAR(9),
	
	PRIMARY KEY(NUMERO)
);

CREATE TABLE ex53.Farmaco(
	NUMERO			INT,
	NOME			VARCHAR(20)		NOT NULL,
	FORMULA			VARCHAR(20)		NOT NULL,
	PRESCRICAO		INT,

	PRIMARY KEY(NUMERO, NOME),
	FOREIGN KEY(NUMERO) REFERENCES ex53.Farmaceutica(NUMERO),
	FOREIGN KEY(PRESCRICAO) REFERENCES ex53.Prescricao(NUMERO)
);

CREATE TABLE ex53.Venda(
	NOME_FARMACO	VARCHAR(20),
	NR_FARMACEUTICA	INT,
	FARMACIA		VARCHAR(20),

	PRIMARY KEY(NR_FARMACEUTICA, NOME_FARMACO, FARMACIA),
	FOREIGN KEY(NR_FARMACEUTICA, NOME_FARMACO) REFERENCES ex53.Farmaco(NUMERO, NOME),
);

CREATE TABLE ex53.Farmacia(
	NOME			VARCHAR(20),
	ENDERECO		VARCHAR(20)		NOT NULL,
	TELEFONE		VARCHAR(9)

	PRIMARY KEY(NOME)
);

ALTER TABLE ex53.Venda
	ADD CONSTRAINT NOMEFARMACIA	FOREIGN KEY(FARMACIA) REFERENCES ex53.Farmacia(NOME);