use p2g5;

-- Drop Section
DROP VIEW MOTORCYCLE_INFO;
DROP VIEW STOCK_BIKE_INFO;
DROP VIEW RENT_BIKE_INFO;
DROP VIEW CLIENT_INFO;
DROP VIEW SALESMAN_SALES;
DROP VIEW SALESMAN_INFO;
DROP VIEW MECHANIC_INFO;
DROP VIEW STAND_LOCALIZATION;
DROP VIEW MOTOSTATION_LOCALIZATION;
DROP VIEW vw_SALES;
DROP VIEW vw_REVISIONS;
DROP VIEW vw_RENTS;
DROP VIEW STAFF_SALESMEN;
DROP VIEW STAFF_MECHANICS;

-- Views
GO
CREATE VIEW MOTORCYCLE_INFO AS
	SELECT BRAND + ' ' + MODEL + ' ' + CONVERT(varchar, CC) AS Motorcycle FROM MOTORCYCLE;
GO
---------------------------------------------------

GO
CREATE VIEW STOCK_BIKE_INFO AS
	SELECT BRAND + ' ' + MODEL + ' ' + CONVERT(varchar, CC) AS Motorcycle
	FROM MOTORCYCLE JOIN STOCK_BIKE ON MOTORCYCLE.FRAME_NO=STOCK_BIKE.FRAME_NO;
GO
---------------------------------------------------

GO
CREATE VIEW RENT_BIKE_INFO AS
	SELECT BRAND + ' ' + MODEL + ' ' + CONVERT(varchar, CC) AS Motorcycle
	FROM MOTORCYCLE JOIN RENTABLE_BIKE ON MOTORCYCLE.FRAME_NO=RENTABLE_BIKE.FRAME_NO;
GO
---------------------------------------------------

GO
CREATE VIEW SALESMAN_SALES AS
	SELECT S_NAME As Salesman, C_NAME As Client,  
	BRAND + ' ' + MODEL + ' ' + CONVERT(varchar, CC) AS Motorcycle,SALE.PRICE As Price
	FROM ((((SALE JOIN SALESMAN ON SELLER=NUMBER)
	JOIN STAFF_MEMBER ON SELLER=STAFF_MEMBER.NUMBER)
	JOIN MOTORCYCLE ON MOTORCYCLE.FRAME_NO = SALE.MOTORCYCLE)
	JOIN CLIENT ON CLIENT.NIF=SALE.CLIENT)
GO
---------------------------------------------------

GO
CREATE VIEW CLIENT_INFO AS
	SELECT C_NAME + ' - ' + CONVERT(varchar,NIF) AS Client FROM CLIENT;
GO

---------------------------------------------------

GO
CREATE VIEW SALESMAN_INFO AS
	SELECT S_NAME + ' - ' + CONVERT(varchar, SALESMAN.NUMBER) AS Salesman 
	FROM SALESMAN JOIN STAFF_MEMBER ON SALESMAN.NUMBER=STAFF_MEMBER.NUMBER;
GO
---------------------------------------------------

GO
CREATE VIEW MECHANIC_INFO AS
	SELECT S_NAME + ' - ' + CONVERT(varchar, MECHANIC.NUMBER) AS Mechanic 
	FROM MECHANIC JOIN STAFF_MEMBER ON MECHANIC.NUMBER=STAFF_MEMBER.NUMBER;
GO
---------------------------------------------------

GO
CREATE VIEW STAND_LOCALIZATION AS
	SELECT NUMBER, LOCALIZATION FROM STAND;
GO
---------------------------------------------------

GO
CREATE VIEW MOTOSTATION_LOCALIZATION AS
	SELECT NUMBER, LOCALIZATION FROM MOTO_STATION;
GO
---------------------------------------------------


GO
CREATE VIEW vw_SALES 
AS
	SELECT INVOICE_NO AS Invoice, S_DATE AS Date, BRAND + ' ' + MODEL AS Motorcycle
	FROM (((SALE JOIN SALESMAN ON SELLER=NUMBER)
	JOIN STAFF_MEMBER ON SALESMAN.NUMBER=STAFF_MEMBER.NUMBER)
	JOIN MOTORCYCLE ON MOTORCYCLE=FRAME_NO);
GO 
---------------------------------------------------

GO
CREATE VIEW vw_REVISIONS AS 
	SELECT REVISION.REVISION_NO AS Number, REVISION.R_DATE as Date, BRAND + ' ' + MODEL AS Motorcycle
	FROM (((REVISION JOIN MECHANIC ON REVISION.MECHANIC=MECHANIC.NUMBER)
	JOIN STAFF_MEMBER ON MECHANIC.NUMBER = STAFF_MEMBER.NUMBER)
	JOIN MOTORCYCLE ON MOTORCYCLE.FRAME_NO=REVISION.FRAME_NO);
GO
---------------------------------------------------

GO
CREATE VIEW vw_RENTS AS
	SELECT R_DATE AS Date, BRAND + ' ' + MODEL AS Motorcycle
	FROM (((RENT JOIN MOTORCYCLE ON RENT.FRAME_NO=MOTORCYCLE.FRAME_NO)
	JOIN RENTABLE_BIKE ON RENT.FRAME_NO=RENTABLE_BIKE.FRAME_NO)
	JOIN MOTO_STATION ON RENTABLE_BIKE.MOTO_STATION=MOTO_STATION.NUMBER);
GO
---------------------------------------------------

GO 
CREATE VIEW STAFF_SALESMEN AS 
	SELECT Member.NUMBER, Member.S_NAME, LOCALIZATION
	FROM ((SALESMAN JOIN STAFF_MEMBER AS Member ON SALESMAN.NUMBER = Member.NUMBER)
	JOIN STAND ON SALESMAN.WORK_STAND=STAND.NUMBER);
GO
---------------------------------------------------

GO 
CREATE VIEW STAFF_MECHANICS AS 
	SELECT Member.NUMBER, Member.S_NAME, LOCALIZATION
	FROM ((MECHANIC JOIN STAFF_MEMBER AS Member ON MECHANIC.NUMBER = Member.NUMBER)
	JOIN WORKSHOP ON MECHANIC.WORK_WORKSHOP=WORKSHOP.NUMBER);
GO
---------------------------------------------------

