--CREATE SCHEMA ex41 AUTHORIZATION "p2g5";
CREATE TABLE ex41.Cliente(
	NIF			INT,
	NOME		VARCHAR(15),
	ENDERECO	VARCHAR(20),
	NR_CARTA	INT,		
	PRIMARY KEY(NIF)
);

CREATE TABLE ex41.Aluguer(
	N_ALUGUER		INT,
	DURACAO			INT,
	DATA_ALUGUER	DATE,
	TITULAR			INT			NOT NULL,
	LOCAL_ALUGUER	INT			NOT NULL,
	OBJETO			VARCHAR(6)	NOT NULL

	PRIMARY KEY(N_ALUGUER),
	FOREIGN KEY (TITULAR) REFERENCES ex41.Cliente(NIF),
);

CREATE TABLE ex41.Balcao(
	N_BALCAO		INT,
	NOME			VARCHAR(10),
	ENDERECO		VARCHAR(20),

	PRIMARY KEY(N_BALCAO)
);

CREATE TABLE ex41.Veiculo(
	MATRICULA		VARCHAR(6),
	MARCA			VARCHAR(10),
	ANO				INT,
	TIPO			INT			NOT NULL,

	PRIMARY KEY(MATRICULA),
);

CREATE TABLE ex41.TipoVeiculo(
	CODIGO			INT,
	AR_COND			BIT,
	DESIGNACAO		VARCHAR(10),

	PRIMARY KEY(CODIGO)
);

CREATE TABLE ex41.Ligeiro(
	CODIGO			INT,
	N_LUGARES		INT,
	COMBUSTIVEL		VARCHAR(5),
	PORTAS			INT,

	PRIMARY KEY(CODIGO),
	FOREIGN KEY(CODIGO) REFERENCES ex41.TipoVeiculo(CODIGO)
);

CREATE TABLE ex41.Pesado(
	CODIGO			INT,
	PESO			INT,
	PASSAGEIROS		BIT,

	PRIMARY KEY(CODIGO),
	FOREIGN KEY(CODIGO) REFERENCES ex41.TipoVeiculo(CODIGO)
);


CREATE TABLE ex41.Similaridade(
	TIPO1			INT,
	TIPO2			INT,
	
	PRIMARY KEY(TIPO1, TIPO2),
	FOREIGN KEY(TIPO1) REFERENCES ex41.TipoVeiculo(CODIGO),
	FOREIGN KEY(TIPO2) REFERENCES ex41.TipoVeiculo(CODIGO),
	
);

ALTER TABLE ex41.Aluguer	
	ADD CONSTRAINT LOCALBALCAO FOREIGN KEY(LOCAL_ALUGUER) REFERENCES ex41.Balcao(N_BALCAO),
		CONSTRAINT OBJMATRICULA FOREIGN KEY(OBJETO)		  REFERENCES ex41.Veiculo(MATRICULA);
ALTER TABLE ex41.Veiculo
	ADD CONSTRAINT CODVEICULO FOREIGN KEY(TIPO) REFERENCES ex41.TipoVeiculo(CODIGO);
