-- CREATE SCHEMA ex42;

CREATE TABLE ex42.Airport(
	AIRPORT_CODE	INT,
	CITY			VARCHAR(10),
	AP_STATE		VARCHAR(10),
	NAME			VARCHAR(20),		
	PRIMARY KEY(AIRPORT_CODE)
);

CREATE TABLE ex42.Can_Land(
	AIRPORT			INT,
	APlane_TYPE		VARCHAR(10),

	PRIMARY KEY(AIRPORT, APlane_TYPE),
	FOREIGN KEY (AIRPORT) REFERENCES ex42.Airport(AIRPORT_CODE),
);

CREATE TABLE ex42.Airplane_Type(
	T_Name			VARCHAR(10),
	COMPANY			VARCHAR(10),
	MAX_SEATS		INT,

	PRIMARY KEY(T_Name)
);

CREATE TABLE ex42.Airplane(
	AIRPLANE_ID		INT,
	TOTAL_NR_SEATS	INT,
	AP_Type			VARCHAR(10)		NOT NULL,


	PRIMARY KEY(AIRPLANE_ID),
	FOREIGN KEY (AP_Type) REFERENCES ex42.Airplane_Type(T_Name)
);

CREATE TABLE ex42.Fare(
	NUMBER			INT,
	CODE			INT,
	AMOUNT			INT,
	RESTRICTIONS	VARCHAR(10),

	PRIMARY KEY(NUMBER, CODE)
);


CREATE TABLE ex42.Flight(
	NUMBER			INT,
	AIRLINE			VARCHAR(10),
	WEEKDAYS		VARCHAR(10),

	PRIMARY KEY(NUMBER)
);

CREATE TABLE ex42.Flight_leg(
	NUMBER			INT,
	LEG_NR			INT,
	AR_AIP			INT		NOT NULL,
	DP_AIP			INT		NOT NULL,
	WEEKDAYS		VARCHAR(10),
	AR_TIME			DATE	NOT NULL,
	DP_TIME			DATE	NOT NULL,

	PRIMARY KEY(NUMBER, LEG_NR),
	FOREIGN KEY(NUMBER) REFERENCES ex42.Flight(NUMBER),
	FOREIGN KEY(AR_AIP) REFERENCES ex42.Airport(AIRPORT_CODE),
	FOREIGN KEY(DP_AIP) REFERENCES ex42.Airport(AIRPORT_CODE)

);


CREATE TABLE ex42.Leg_Instance(
	AR_AIRPORT		INT,
	DEP_AIRPORT		INT,
	AIRPLANE		INT		NOT NULL,
	NUMBER			INT		NOT NULL,
	LEG_NR			INT		NOT NULL,
	LEG_DATE		DATE,
	NR_SEATS		INT,
	
	PRIMARY KEY(NUMBER, LEG_NR, LEG_DATE),
	FOREIGN KEY(AR_AIRPORT) REFERENCES ex42.Airport(AIRPORT_CODE),
	FOREIGN KEY(DEP_AIRPORT) REFERENCES ex42.Airport(AIRPORT_CODE),
	FOREIGN KEY(AIRPLANE) REFERENCES ex42.Airplane(AIRPLANE_ID),
	FOREIGN KEY(NUMBER, LEG_NR) REFERENCES ex42.Flight_leg(NUMBER, LEG_NR),

);

CREATE TABLE ex42.Seat(
	NUMBER			INT				NOT NULL,
	LEG_NR			INT				NOT NULL,
	SEAT_DATE		DATE			NOT NULL,
	SEAT_NR			INT,
	CUSTM_NAME		VARCHAR(20)		NOT NULL,
	PHONE_NR		INT				NOT NULL,

	PRIMARY KEY(NUMBER, LEG_NR, SEAT_DATE, SEAT_NR),
	FOREIGN KEY(NUMBER, LEG_NR, SEAT_DATE) REFERENCES ex42.Leg_Instance(NUMBER, LEG_NR, LEG_DATE),

);
	-- FOREIGN KEY(NUMBER) REFERENCES ex42.Flight(NUMBER)

ALTER TABLE ex42.Can_Land
	ADD CONSTRAINT LANDTYPE FOREIGN KEY(APlane_TYPE) REFERENCES ex42.Airplane_Type(T_Name);
ALTER TABLE ex42.Fare
	ADD CONSTRAINT FAREFLIGHTNR FOREIGN KEY(NUMBER) REFERENCES ex42.Flight(NUMBER);
