--CREATE SCHEMA ex43;

CREATE TABLE ex43.Produto(
	CODIGO		INT,
	NOME		VARCHAR(20),
	PRECO		INT				CHECK(PRECO >= 0),
	IVA			INT				CHECK(IVA >= 0 AND IVA <= 100),
	STOCK		INT				CHECK(STOCK > 0),
	
	PRIMARY KEY(CODIGO)

);

CREATE TABLE ex43.Conteudo(
	PRODUTO			INT,
	ENCOMENDA		INT,
	UNIDADES		INT			CHECK(UNIDADES >= 0),

	PRIMARY KEY(PRODUTO, ENCOMENDA),
	FOREIGN KEY(PRODUTO) REFERENCES ex43.Produto(CODIGO)
);


CREATE TABLE ex43.Encomenda(
	NUMERO			INT,
	DATA_ENCOMENDA	DATE,
	FORNECEDOR		INT			NOT NULL,

	PRIMARY KEY(NUMERO)
	
);

CREATE TABLE ex43.Fornecedor(
	NIF				INT,
	TIPO			INT			NOT NULL,
	NOME			VARCHAR(20),
	FAX				INT,
	ENDERECO		VARCHAR(20),
	CODIGO			INT,
	PAGAMENTO		INT			CHECK(PAGAMENTO > 0),

	PRIMARY KEY(NIF)
);

CREATE TABLE ex43.Tipo_Fornecedor(
	CODIGO		INT,
	DESIGN		VARCHAR(20),

	PRIMARY KEY(CODIGO)
);

ALTER TABLE ex43.Conteudo
	ADD CONSTRAINT CNTDENCOMENDA FOREIGN KEY(ENCOMENDA) REFERENCES ex43.Encomenda(NUMERO);
	
ALTER TABLE ex43.Encomenda
	ADD CONSTRAINT NIFENCOMENDA FOREIGN KEY(FORNECEDOR) REFERENCES ex43.Fornecedor(NIF);

ALTER TABLE ex43.Fornecedor
	ADD CONSTRAINT TIPOFORNECEDOR FOREIGN KEY(TIPO) REFERENCES ex43.Tipo_Fornecedor(CODIGO);