--CREATE SCHEMA ex44;

CREATE TABLE ex44.Medico(
	SNS				INT,
	NOME			VARCHAR(20)		NOT NULL,
	ESPECIALIDADE	VARCHAR(20),

	PRIMARY KEY(SNS)

);

CREATE TABLE ex44.Paciente(
	NR_UTENTE		INT,
	NOME			VARCHAR(20)		NOT NULL,
	DATA_NASC		DATE			NOT NULL,
	ENDERECO		VARCHAR(20),

	PRIMARY KEY(NR_UTENTE)

);

CREATE TABLE ex44.Prescricao(
	NUMERO			INT,
	MEDICO			INT		NOT NULL,
	PACIENTE		INT		NOT NULL,

	PRIMARY KEY(NUMERO),
	FOREIGN KEY(MEDICO) REFERENCES ex44.Medico(SNS),
	FOREIGN KEY(PACIENTE) REFERENCES ex44.Paciente(NR_UTENTE)

);

CREATE TABLE ex44.Farmaceutica(
	NUMERO			INT,
	NOME			VARCHAR(20)		NOT NULL,
	ENDERECO		VARCHAR(20)		NOT NULL,
	TELEFONE		VARCHAR(9),
	
	PRIMARY KEY(NUMERO)
);

CREATE TABLE ex44.Farmaco(
	NUMERO			INT,
	NOME			VARCHAR(20)		NOT NULL,
	FORMULA			VARCHAR(20)		NOT NULL,
	PRESCRICAO		INT,

	PRIMARY KEY(NUMERO, NOME),
	FOREIGN KEY(NUMERO) REFERENCES ex44.Farmaceutica(NUMERO),
	FOREIGN KEY(PRESCRICAO) REFERENCES ex44.Prescricao(NUMERO)
);

CREATE TABLE ex44.Venda(
	NOME_FARMACO	VARCHAR(20),
	NR_FARMACEUTICA	INT,
	FARMACIA		VARCHAR(20),

	PRIMARY KEY(NR_FARMACEUTICA, NOME_FARMACO, FARMACIA),
	FOREIGN KEY(NR_FARMACEUTICA, NOME_FARMACO) REFERENCES ex44.Farmaco(NUMERO, NOME),
	-- FOREIGN KEY(FARMACIA) REFERENCES ex44.Farmacia(NOME)

);

CREATE TABLE ex44.Farmacia(
	NOME			VARCHAR(20),
	ENDERECO		VARCHAR(20)		NOT NULL,
	TELEFONE		VARCHAR(9)

	PRIMARY KEY(NOME)
);

ALTER TABLE ex44.Venda
	ADD CONSTRAINT NOMEFARMACIA	FOREIGN KEY(FARMACIA) REFERENCES ex44.Farmacia(NOME);