CREATE SCHEMA ex45;
GO

-- Init Section
CREATE TABLE ex45.Instituicao(
	NOME			VARCHAR(20),
	ENDERECO		VARCHAR(20),

	PRIMARY KEY(NOME)
);

CREATE TABLE ex45.Pessoa(
	EMAIL			VARCHAR(20),
	NOME			VARCHAR(20),
	INSTITUICAO		VARCHAR(20)		NOT NULL,

	PRIMARY KEY(EMAIL),
	FOREIGN KEY(INSTITUICAO) REFERENCES ex45.Instituicao(NOME)
);

CREATE TABLE ex45.Participante(
	EMAIL			VARCHAR(20),
	DATA_IN			DATE,
	MORADA			VARCHAR(20),

	PRIMARY KEY(EMAIL),
	FOREIGN KEY(EMAIL) REFERENCES ex45.Pessoa(EMAIL)
);

CREATE TABLE ex45.Estudante(
	EMAIL			VARCHAR(20),
	COMPROVATIVO	VARCHAR(20),

	PRIMARY KEY(EMAIL),
	FOREIGN KEY(EMAIL) REFERENCES ex45.Participante(EMAIL)
);

CREATE TABLE ex45.Nao_Estudante(
	EMAIL			VARCHAR(20),
	REF_BANC		INT,

	PRIMARY KEY(EMAIL),
	FOREIGN KEY(EMAIL) REFERENCES ex45.Participante(EMAIL)
);

CREATE TABLE ex45.Autor(
	EMAIL			VARCHAR(20),

	PRIMARY KEY(EMAIL),
	FOREIGN KEY(EMAIL) REFERENCES ex45.Pessoa(EMAIL)
);

CREATE TABLE ex45.Artigo(
	NR_REG			INT,

	PRIMARY KEY(NR_REG),
);

CREATE TABLE ex45.Escreve(
	AUTOR			VARCHAR(20),
	ARTIGO			INT,

	PRIMARY KEY(AUTOR, ARTIGO),
	FOREIGN KEY(AUTOR) REFERENCES ex45.Autor(EMAIL),
	FOREIGN KEY(ARTIGO) REFERENCES ex45.Artigo(NR_REG)
);
