CREATE SCHEMA ex46;

-- Delete Section
DROP TABLE ex46.Est_Participa;
DROP TABLE ex46.Prof_Participa;
DROP TABLE ex46.Projeto;
DROP TABLE ex46.Graduado;
ALTER TABLE ex46.Professor
	DROP CONSTRAINT TRABALHA;
DROP TABLE ex46.Departamento;
DROP TABLE ex46.Professor;

-- Init Section
CREATE TABLE ex46.Professor(
	MEC				INT,
	NOME			VARCHAR(20),
	AREA			VARCHAR(20),
	CATEGORIA		VARCHAR(20),
	NASC			DATE,
	DEPARTAMENTO	VARCHAR(20)		NOT NULL,
	DEDICACAO		INT				CHECK(DEDICACAO > 0 AND DEDICACAO <= 100),

	PRIMARY KEY(MEC)
);

CREATE TABLE ex46.Departamento(
	NOME			VARCHAR(20),
	MORADA			VARCHAR(20),
	DIRIGENTE		INT,

	PRIMARY KEY(NOME),
	FOREIGN KEY(DIRIGENTE) REFERENCES ex46.Professor(MEC)
);

ALTER TABLE ex46.Professor
	ADD CONSTRAINT TRABALHA FOREIGN KEY(DEPARTAMENTO) REFERENCES ex46.Departamento(NOME);

CREATE TABLE ex46.Graduado(
	MEC				INT,
	NOME			VARCHAR(20),
	NASC			DATE,
	SUPERVISOR		INT				NOT NULL,
	DEPARTAMENTO	VARCHAR(20)		NOT NULL,
	GRAU			VARCHAR(20),
	CONSELHEIRO		INT				NOT NULL,

	PRIMARY KEY(MEC),
	FOREIGN KEY(SUPERVISOR) REFERENCES ex46.Professor(MEC),
	FOREIGN KEY(DEPARTAMENTO) REFERENCES ex46.Departamento(NOME),
	FOREIGN KEY(CONSELHEIRO) REFERENCES ex46.Graduado(MEC)
);

CREATE TABLE ex46.Projeto(
	ID				INT,
	NOME			VARCHAR(20),
	ORÇAMENTO		INT,
	ENT_FIN			VARCHAR(20),
	INIT_DATE		DATE,
	EXIT_DATE		DATE,
	GESTOR			INT				NOT NULL,

	PRIMARY KEY(ID),
	FOREIGN KEY(GESTOR) REFERENCES ex46.Professor(MEC)
);

CREATE TABLE ex46.Est_Participa(
	MEC				INT,
	PROJETO			INT,

	PRIMARY KEY(MEC, PROJETO),
	FOREIGN KEY(MEC) REFERENCES ex46.Graduado(MEC),
	FOREIGN KEY(PROJETO) REFERENCES ex46.Projeto(ID)
);

CREATE TABLE ex46.Prof_Participa(
	MEC				INT,
	PROJETO			INT,

	PRIMARY KEY(MEC, PROJETO),
	FOREIGN KEY(MEC) REFERENCES ex46.Professor(MEC),
	FOREIGN KEY(PROJETO) REFERENCES ex46.Projeto(ID)
);


